In [106]:
import pandas as pd

In [107]:
df=pd.read_excel('ideation.xlsx')

In [108]:
df.dtypes

patient_id                       int64
gender                          object
age                              int64
emoployment                     object
description_of_health_status    object
label                           object
dtype: object

In [109]:
df.columns

Index(['patient_id', 'gender', 'age', 'emoployment',
       'description_of_health_status', 'label'],
      dtype='object')

In [110]:
df.label

0         suicidal
1     non suicidal
2         suicidal
3     non suicidal
4     non suicidal
5     non suicidal
6     non suicidal
7         suicidal
8     non suicidal
9     non suicidal
10        suicidal
11    non suicidal
12    non suicidal
13    non suicidal
14        suicidal
15    non suicidal
16    non suicidal
17    non suicidal
18        suicidal
19    non suicidal
20        suicidal
21    non suicidal
22    non suicidal
23        suicidal
24    non suicidal
25    non suicidal
26    non suicidal
27        suicidal
28    non suicidal
29        suicidal
30    non suicidal
31        suicidal
32    non suicidal
33    non suicidal
34    non suicidal
35        suicidal
36    non suicidal
37    non suicidal
38             NaN
39    non suicidal
40        suicidal
41    non suicidal
42    non suicidal
43    non suicidal
44    non suicidal
45             NaN
46             NaN
47        suicidal
48    non suicidal
49    non suicidal
50    non suicidal
51             NaN
52    non su

In [111]:
df['label'].dropna().size

55

In [112]:
df1=df.where(df.label=="suicidal")
df1=df1.dropna()
df1
dataframe=df1
dataframe

patient_id  gender   age         emoployment  \
0          1.0    male  25.0    software analyst   
2          3.0    male  26.0    software analyst   
7          8.0  female  25.0    software analyst   
10        11.0    male  26.0           carpenter   
14        15.0  female  34.0    software analyst   
18        19.0    male  28.0    software analyst   
20        21.0  female  30.0  office-coordinator   
23        24.0    male  27.0    software analyst   
27        28.0    male  26.0    police constable   
29        30.0  female  25.0             testing   
31        32.0    male  26.0    software analyst   
35        36.0    male  26.0               clerk   
40        41.0  female  30.0              driver   
47        48.0  female  30.0      military major   
55        56.0  female  26.0           carpenter   
59        60.0  female  31.0    software analyst   

                         description_of_health_status     label  
0   umm.. Subjects condition turned oput to be %*^...  suicidal  
2   .subject condition cannot be controlled, love ...  suicidal  
7                            stress&^%^( *& from  job  suicidal  
10                             stress from%*^$@#^ job  suicidal  
14                                    stress from job  suicidal  
18                             past trauma,depression  suicidal  
20                                    stress from job  suicidal  
23                             past trauma,depression  suicidal  
27                                autoimmune disorder  suicidal  
29                             past trauma,depression  suicidal  
31                             past trauma,depression  suicidal  
35                             past trauma,depression  suicidal  
40                                autoimmune disorder  suicidal  
47                             past trauma,depression  suicidal  
55                             past trauma,depression  suicidal  
59                                 husband harrasment  suicidal

In [113]:
print("total number is",df1['age'].size)

total number is 16


In [114]:
dataframe.gender.value_counts()

female    8
male      8
Name: gender, dtype: int64

In [115]:
df.gender.value_counts()

female    32
male      28
Name: gender, dtype: int64

In [116]:
df['description_of_health_status']

0     umm.. Subjects condition turned oput to be %*^...
1     patients condition%*^$@#^is undercontrol, its ...
2     .subject condition cannot be controlled, love ...
3                        patient almost coped from past
4                  stress from personal%*^$@#^ problems
5                    his job is not satisfactory%*^$@#^
6              facing  personal problems,can &^be cured
7                              stress&^%^( *& from  job
8              facing  personal problems,can &^be cured
9         facing  personal%*^$@#^ problems,can be cured
10                               stress from%*^$@#^ job
11       facing  personal problems,%*^$@#^ can be cured
12             facing  personal problems,can &^be cured
13                               past trauma,depression
14                                      stress from job
15             facing  personal problems,can &^be cured
16                  facing common immune%*^$@#^ illness
17             facing  personal problems,can &^b

In [117]:
import re
import nltk

In [118]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer as wnl

In [119]:
leng=df['description_of_health_status'].size
data=df['description_of_health_status']
text=[]
for i in data:
    s=re.sub(r'[^\w\s]','',i)
    s=nltk.word_tokenize(s)
    text.append(s)
    
porter=PorterStemmer()
wordnetlemmatizer=wnl()
text1=[]
sent=[]
for i in range(len(text)):
    for j in range(len(text[i])):
        s=wordnetlemmatizer.lemmatize(text[i][j])
        sent.append(s)
    text1.append(sent)
    sent=[]
text=text1
text1=[]
for i in range(len(text)):
    for j in range(len(text[i])):
        s=porter.stem(text[i][j])
        sent.append(s)
    text1.append(sent)
    sent=[]

text=text1
text1=[]


In [120]:
for i in range(len(text)):
    for j in range(len(text[i])):
        if text[i][j] is int:
            print(i,j)

In [121]:
text

[['umm',
  'subject',
  'condit',
  'turn',
  'oput',
  'to',
  'be',
  'due',
  'to',
  'trauma'],
 ['patient', 'conditioni', 'undercontrol', 'it', 'is', 'hi', 'addict'],
 ['subject', 'condit', 'can', 'not', 'be', 'control', 'love', 'failur'],
 ['patient', 'almost', 'cope', 'from', 'past'],
 ['stress', 'from', 'person', 'problem'],
 ['hi', 'job', 'is', 'not', 'satisfactori'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['stress', 'from', 'job'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['stress', 'from', 'job'],
 ['face', 'person', 'problem', 'can', 'be', 'cure'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['past', 'traumadepress'],
 ['stress', 'from', 'job'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['face', 'common', 'immun', 'ill'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['past', 'traumadepress'],
 ['face', 'person', 'problemscan', 'be', 'cure'],
 ['stress', 'from', 'job'],
 ['face', 'p

In [122]:
df1=df

In [123]:
df1=df1.rename(columns={"description_of_health_status":"description_of_health_status_changed"})

In [124]:
df1['description_of_health_status_changed']=text

In [125]:
from sklearn.feature_extraction.text import CountVectorizer as cv

In [126]:
Cv=cv()

In [127]:
x=Cv.fit_transform(text[0]).toarray()
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [128]:
from sklearn.decomposition import PCA

In [129]:
pca=PCA(n_components=2)

In [130]:
target=df1['label'].values

In [131]:
df1.columns

Index(['patient_id', 'gender', 'age', 'emoployment',
       'description_of_health_status_changed', 'label'],
      dtype='object')

In [132]:
from sklearn.feature_extraction.text import CountVectorizer as CV

In [133]:
df1['description_of_health_status_changed']=[" ".join(d) for d in df1['description_of_health_status_changed'].values]

In [134]:
df

patient_id  gender  age          emoployment  \
0            1    male   25     software analyst   
1            2  female   30            carpenter   
2            3    male   26     software analyst   
3            4    male   26               no job   
4            5    male   38          auto driver   
5            6    male   27    animaion director   
6            7  female   27               no job   
7            8  female   25     software analyst   
8            9  female   30               artist   
9           10  female   26     software analyst   
10          11    male   26            carpenter   
11          12    male   31                actor   
12          13    male   32     software analyst   
13          14  female   33              teacher   
14          15  female   34     software analyst   
15          16  female   25           hr manager   
16          17  female   30     software analyst   
17          18  female   26      looking for job   
18          19    male   28     software analyst   
19          20    male   29          electritian   
20          21  female   30   office-coordinator   
21          22    male   29     software analyst   
22          23  female   30            carpenter   
23          24    male   27     software analyst   
24          25  female   34      looking for job   
25          26  female   25     software analyst   
26          27    male   35               no job   
27          28    male   26     police constable   
28          29  female   26      looking for job   
29          30  female   25              testing   
30          31  female   30  executive assistant   
31          32    male   26     software analyst   
32          33  female   26            carpenter   
33          34    male   36      looking for job   
34          35  female   26  executive assistant   
35          36    male   26                clerk   
36          37  female   25     software analyst   
37          38    male   30      looking for job   
38          39  female   37  executive assistant   
39          40    male   36            carpenter   
40          41  female   30               driver   
41          42    male   26      looking for job   
42          43    male   26     software analyst   
43          44    male   25               no job   
44          45  female   30            carpenter   
45          46  female   38      looking for job   
46          47    male   29  executive assistant   
47          48  female   30       military major   
48          49  female   26     software analyst   
49          50  female   26            carpenter   
50          51  female   25      looking for job   
51          52    male   30  executive assistant   
52          53  female   32               no job   
53          54    male   31      looking for job   
54          55    male   30     software analyst   
55          56  female   26            carpenter   
56          57    male   26  executive assistant   
57          58  female   25      looking for job   
58          59    male   30               no job   
59          60  female   31     software analyst   

                         description_of_health_status         label  
0   umm.. Subjects condition turned oput to be %*^...      suicidal  
1   patients condition%*^$@#^is undercontrol, its ...  non suicidal  
2   .subject condition cannot be controlled, love ...      suicidal  
3                      patient almost coped from past  non suicidal  
4                stress from personal%*^$@#^ problems  non suicidal  
5                  his job is not satisfactory%*^$@#^  non suicidal  
6            facing  personal problems,can &^be cured  non suicidal  
7                            stress&^%^( *& from  job      suicidal  
8            facing  personal problems,can &^be cured  non suicidal  
9       facing  personal%*^$@#^ problems,can be cured  non suicidal  
10                             stress from%*^$@#^ job      su

In [135]:
cv=CV()
ar1=cv.fit_transform(df1['description_of_health_status_changed']).toarray()
print(ar1[0])

[0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 2 1 0 1 1 0 0]


In [136]:
array=ar1
array

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [137]:
df1

patient_id  gender  age          emoployment  \
0            1    male   25     software analyst   
1            2  female   30            carpenter   
2            3    male   26     software analyst   
3            4    male   26               no job   
4            5    male   38          auto driver   
5            6    male   27    animaion director   
6            7  female   27               no job   
7            8  female   25     software analyst   
8            9  female   30               artist   
9           10  female   26     software analyst   
10          11    male   26            carpenter   
11          12    male   31                actor   
12          13    male   32     software analyst   
13          14  female   33              teacher   
14          15  female   34     software analyst   
15          16  female   25           hr manager   
16          17  female   30     software analyst   
17          18  female   26      looking for job   
18          19    male   28     software analyst   
19          20    male   29          electritian   
20          21  female   30   office-coordinator   
21          22    male   29     software analyst   
22          23  female   30            carpenter   
23          24    male   27     software analyst   
24          25  female   34      looking for job   
25          26  female   25     software analyst   
26          27    male   35               no job   
27          28    male   26     police constable   
28          29  female   26      looking for job   
29          30  female   25              testing   
30          31  female   30  executive assistant   
31          32    male   26     software analyst   
32          33  female   26            carpenter   
33          34    male   36      looking for job   
34          35  female   26  executive assistant   
35          36    male   26                clerk   
36          37  female   25     software analyst   
37          38    male   30      looking for job   
38          39  female   37  executive assistant   
39          40    male   36            carpenter   
40          41  female   30               driver   
41          42    male   26      looking for job   
42          43    male   26     software analyst   
43          44    male   25               no job   
44          45  female   30            carpenter   
45          46  female   38      looking for job   
46          47    male   29  executive assistant   
47          48  female   30       military major   
48          49  female   26     software analyst   
49          50  female   26            carpenter   
50          51  female   25      looking for job   
51          52    male   30  executive assistant   
52          53  female   32               no job   
53          54    male   31      looking for job   
54          55    male   30     software analyst   
55          56  female   26            carpenter   
56          57    male   26  executive assistant   
57          58  female   25      looking for job   
58          59    male   30               no job   
59          60  female   31     software analyst   

                description_of_health_status_changed         label  
0   umm subject condit turn oput to be due to trauma      suicidal  
1    patient conditioni undercontrol it is hi addict  non suicidal  
2      subject condit can not be control love failur      suicidal  
3                      patient almost cope from past  non suicidal  
4                         stress from person problem  non suicidal  
5                         hi job is not satisfactori  non suicidal  
6                    face person problemscan be cure  non suicidal  
7                                    stress from job      suicidal  
8                    face person problemscan be cure  non suicidal  
9                    face person problemscan be cure  non suicidal  
10                                   stress from job      suicidal  
11 

In [138]:
array=list(array)
x={'data':array}
df2=pd.DataFrame(x)
df2['data'].values

array([array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 2, 1, 0, 1, 1, 0, 0], dtype=int64),
       array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
       array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
       array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
     

In [240]:
h=df1['description_of_health_status_changed']
h

0     umm subject condit turn oput to be due to trauma
1      patient conditioni undercontrol it is hi addict
2        subject condit can not be control love failur
3                        patient almost cope from past
4                           stress from person problem
5                           hi job is not satisfactori
6                      face person problemscan be cure
7                                      stress from job
8                      face person problemscan be cure
9                      face person problemscan be cure
10                                     stress from job
11                     face person problem can be cure
12                     face person problemscan be cure
13                                  past traumadepress
14                                     stress from job
15                     face person problemscan be cure
16                               face common immun ill
17                     face person problemscan be cure
18        

In [140]:
len(df1.columns)

6

In [141]:
a=df2['data']
df2=df1
df2.rename(columns={"description_of_health_status_changed":"description_of_health_status_changed0"})
df2['description_of_health_status_changed0']=a

In [142]:
df1=df1.iloc[:,:6]

In [143]:
df2.columns

Index(['patient_id', 'gender', 'age', 'emoployment',
       'description_of_health_status_changed', 'label',
       'description_of_health_status_changed0'],
      dtype='object')

In [144]:
from sklearn.preprocessing import LabelEncoder as LE
le=LE()
df2['gender']=le.fit_transform(df2['gender'])
le=LE()
df2['emoployment']=le.fit_transform(df2['emoployment'])
le=LE()
df2['label']=le.fit_transform(df2['label'])

In [145]:
col=['patient_id', 'gender', 'age', 'emoployment','label','description_of_health_status_changed0']
df2=df2.reindex(columns=col)
df2

patient_id  gender  age  emoployment  label  \
0            1       1   25           15      1   
1            2       0   30            4      0   
2            3       1   26           15      1   
3            4       1   26           12      0   
4            5       1   38            3      0   
5            6       1   27            1      0   
6            7       0   27           12      0   
7            8       0   25           15      1   
8            9       0   30            2      0   
9           10       0   26           15      0   
10          11       1   26            4      1   
11          12       1   31            0      0   
12          13       1   32           15      0   
13          14       0   33           16      0   
14          15       0   34           15      1   
15          16       0   25            9      0   
16          17       0   30           15      0   
17          18       0   26           10      0   
18          19       1   28           15      1   
19          20       1   29            7      0   
20          21       0   30           13      1   
21          22       1   29           15      0   
22          23       0   30            4      0   
23          24       1   27           15      1   
24          25       0   34           10      0   
25          26       0   25           15      0   
26          27       1   35           12      0   
27          28       1   26           14      1   
28          29       0   26           10      0   
29          30       0   25           17      1   
30          31       0   30            8      0   
31          32       1   26           15      1   
32          33       0   26            4      0   
33          34       1   36           10      0   
34          35       0   26            8      0   
35          36       1   26            5      1   
36          37       0   25           15      0   
37          38       1   30           10      0   
38          39       0   37            8      2   
39          40       1   36            4      0   
40          41       0   30            6      1   
41          42       1   26           10      0   
42          43       1   26           15      0   
43          44       1   25           12      0   
44          45       0   30            4      0   
45          46       0   38           10      2   
46          47       1   29            8      2   
47          48       0   30           11      1   
48          49       0   26           15      0   
49          50       0   26            4      0   
50          51       0   25           10      0   
51          52       1   30            8      2   
52          53       0   32           12      0   
53          54       1   31           10      2   
54          55       1   30           15      0   
55          56       0   26            4      1   
56          57       1   26            8      0   
57          58       0   25           10      0   
58          59       1   30           12      0   
59          60       0   31           15      1   

                description_of_health_status_changed0  
0   [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...  
1   [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...  
2   [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, ...  
3   [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...  
4   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
6   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
7   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
8   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
9   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
10  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
11  [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
12  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
13  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
14  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..

In [188]:
data=df2.iloc[:,:4]
data

patient_id  gender  age  emoployment
0            1       1   25           15
1            2       0   30            4
2            3       1   26           15
3            4       1   26           12
4            5       1   38            3
5            6       1   27            1
6            7       0   27           12
7            8       0   25           15
8            9       0   30            2
9           10       0   26           15
10          11       1   26            4
11          12       1   31            0
12          13       1   32           15
13          14       0   33           16
14          15       0   34           15
15          16       0   25            9
16          17       0   30           15
17          18       0   26           10
18          19       1   28           15
19          20       1   29            7
20          21       0   30           13
21          22       1   29           15
22          23       0   30            4
23          24       1   27           15
24          25       0   34           10
25          26       0   25           15
26          27       1   35           12
27          28       1   26           14
28          29       0   26           10
29          30       0   25           17
30          31       0   30            8
31          32       1   26           15
32          33       0   26            4
33          34       1   36           10
34          35       0   26            8
35          36       1   26            5
36          37       0   25           15
37          38       1   30           10
38          39       0   37            8
39          40       1   36            4
40          41       0   30            6
41          42       1   26           10
42          43       1   26           15
43          44       1   25           12
44          45       0   30            4
45          46       0   38           10
46          47       1   29            8
47          48       0   30           11
48          49       0   26           15
49          50       0   26            4
50          51       0   25           10
51          52       1   30            8
52          53       0   32           12
53          54       1   31           10
54          55       1   30           15
55          56       0   26            4
56          57       1   26            8
57          58       0   25           10
58          59       1   30           12
59          60       0   31           15

In [181]:
from sklearn import svm
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
coordinates=pca.fit_transform(data)

In [148]:
df2.columns

Index(['patient_id', 'gender', 'age', 'emoployment', 'label',
       'description_of_health_status_changed0'],
      dtype='object')

In [149]:
df2.reindex(columns=col)

patient_id  gender  age  emoployment  label  \
0            1       1   25           15      1   
1            2       0   30            4      0   
2            3       1   26           15      1   
3            4       1   26           12      0   
4            5       1   38            3      0   
5            6       1   27            1      0   
6            7       0   27           12      0   
7            8       0   25           15      1   
8            9       0   30            2      0   
9           10       0   26           15      0   
10          11       1   26            4      1   
11          12       1   31            0      0   
12          13       1   32           15      0   
13          14       0   33           16      0   
14          15       0   34           15      1   
15          16       0   25            9      0   
16          17       0   30           15      0   
17          18       0   26           10      0   
18          19       1   28           15      1   
19          20       1   29            7      0   
20          21       0   30           13      1   
21          22       1   29           15      0   
22          23       0   30            4      0   
23          24       1   27           15      1   
24          25       0   34           10      0   
25          26       0   25           15      0   
26          27       1   35           12      0   
27          28       1   26           14      1   
28          29       0   26           10      0   
29          30       0   25           17      1   
30          31       0   30            8      0   
31          32       1   26           15      1   
32          33       0   26            4      0   
33          34       1   36           10      0   
34          35       0   26            8      0   
35          36       1   26            5      1   
36          37       0   25           15      0   
37          38       1   30           10      0   
38          39       0   37            8      2   
39          40       1   36            4      0   
40          41       0   30            6      1   
41          42       1   26           10      0   
42          43       1   26           15      0   
43          44       1   25           12      0   
44          45       0   30            4      0   
45          46       0   38           10      2   
46          47       1   29            8      2   
47          48       0   30           11      1   
48          49       0   26           15      0   
49          50       0   26            4      0   
50          51       0   25           10      0   
51          52       1   30            8      2   
52          53       0   32           12      0   
53          54       1   31           10      2   
54          55       1   30           15      0   
55          56       0   26            4      1   
56          57       1   26            8      0   
57          58       0   25           10      0   
58          59       1   30           12      0   
59          60       0   31           15      1   

                description_of_health_status_changed0  
0   [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...  
1   [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...  
2   [0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, ...  
3   [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...  
4   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
6   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
7   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
8   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
9   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
10  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
11  [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...  
12  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
13  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
14  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..

In [150]:
df2.columns

Index(['patient_id', 'gender', 'age', 'emoployment', 'label',
       'description_of_health_status_changed0'],
      dtype='object')

In [151]:
y_values=df2['label'].values
y_values

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       0, 2, 2, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 1])

In [152]:
xtr=coordinates[:int(len(coordinates)/2)]
xte=coordinates[int(len(coordinates)/2):]
xval=coordinates[int(len(coordinates)/4):int(len(coordinates)/2)+int(len(coordinates)/4)]

In [297]:
x_values=df2.iloc[:,:4]
y_values=df2['label'].values
y_values,x_values

(array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
        0, 2, 2, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 0, 1]),
     patient_id  gender  age  emoployment
 0            1       1   25           15
 1            2       0   30            4
 2            3       1   26           15
 3            4       1   26           12
 4            5       1   38            3
 5            6       1   27            1
 6            7       0   27           12
 7            8       0   25           15
 8            9       0   30            2
 9           10       0   26           15
 10          11       1   26            4
 11          12       1   31            0
 12          13       1   32           15
 13          14       0   33           16
 14          15       0   34           15
 15          16       0   25            9
 16          17       0   30           15
 17          18       0   26          

In [298]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_values,y_values)

# svm

In [319]:
s=svm.SVC(kernel="linear")
s.fit(x_train,y_train)

SVC(kernel='linear')

In [320]:
svm_predicted=s.predict(x_train)

In [321]:
s.score(x_test,y_test)

0.6

In [322]:
y_values=df2['description_of_health_status_changed0']

In [323]:
svm_predicted

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

## desicion tree

In [158]:
from sklearn.tree import DecisionTreeClassifier

In [159]:
dtc=DecisionTreeClassifier()

In [291]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [292]:
dtc.predict(data)

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 2, 2, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 1])

In [294]:
dtc.score(data,target)

0.8666666666666667

In [295]:
import numpy as np

In [259]:
df2.columns

Index(['patient_id', 'gender', 'age', 'emoployment', 'label',
       'description_of_health_status_changed0'],
      dtype='object')

In [ ]:
dtc.fit(x_values,y_values)

In [251]:
tokenized_data=[]
for i in range(len(data)):
    h=nltk.word_tokenize(data[i])
    tokenized_data.append(h)
tokenized_data=np.array(tokenized_data,dtype=object)
tokenized_data=tokenized_data.reshape(-1)
tokenized_data

KeyError: 0

In [177]:
x_data=[]
for i in range(len(data)):
    x=t.fit_transform(tokenized_data[0]).toarray()
    x_data.append(x)
x_data=np.array(x_data)
#x_data.reshape()
x_data.shape

NameError: name 'tokenized_data' is not defined

In [ ]:
x_data=x_data.reshape(1,-1)

In [ ]:
#x_data.reshape(-1,1)
x_data.shape

In [ ]:
tokenized_data=tokenized_data.reshape(-1,1)
tokenized_data.shape

## naive bayes

In [287]:
from sklearn.naive_bayes import MultinomialNB
multinomialnb = MultinomialNB()
multinomialnb.fit(x_train,y_train)

MultinomialNB()

In [288]:
multinomialnb.predict(data)

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0,
       2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [290]:
multinomialnb.score(x_test,y_test)

0.4666666666666667

## tfidVectorizer

In [163]:
from sklearn.feature_extraction.text import TfidfVectorizer  as tfidv

In [170]:
t=tfidv()

In [171]:
df1.columns

Index(['patient_id', 'gender', 'age', 'emoployment',
       'description_of_health_status_changed', 'label'],
      dtype='object')

In [172]:
s1=df1['description_of_health_status_changed']

In [175]:
arrai=t.fit_transform(s1).toarray()

In [176]:
arrai

array([[0.        , 0.        , 0.        , ..., 0.31580897, 0.        ,
        0.        ],
       [0.        , 0.3930014 , 0.        , ..., 0.        , 0.3930014 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

## LDA

In [186]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [198]:
lda=LDA(n_components=1)

In [199]:
y_data=df2['label'].values

In [200]:
values=lda.fit_transform(data,y_data)

In [241]:
data

patient_id  gender  age  emoployment
0            1       1   25           15
1            2       0   30            4
2            3       1   26           15
3            4       1   26           12
4            5       1   38            3
5            6       1   27            1
6            7       0   27           12
7            8       0   25           15
8            9       0   30            2
9           10       0   26           15
10          11       1   26            4
11          12       1   31            0
12          13       1   32           15
13          14       0   33           16
14          15       0   34           15
15          16       0   25            9
16          17       0   30           15
17          18       0   26           10
18          19       1   28           15
19          20       1   29            7
20          21       0   30           13
21          22       1   29           15
22          23       0   30            4
23          24       1   27           15
24          25       0   34           10
25          26       0   25           15
26          27       1   35           12
27          28       1   26           14
28          29       0   26           10
29          30       0   25           17
30          31       0   30            8
31          32       1   26           15
32          33       0   26            4
33          34       1   36           10
34          35       0   26            8
35          36       1   26            5
36          37       0   25           15
37          38       1   30           10
38          39       0   37            8
39          40       1   36            4
40          41       0   30            6
41          42       1   26           10
42          43       1   26           15
43          44       1   25           12
44          45       0   30            4
45          46       0   38           10
46          47       1   29            8
47          48       0   30           11
48          49       0   26           15
49          50       0   26            4
50          51       0   25           10
51          52       1   30            8
52          53       0   32           12
53          54       1   31           10
54          55       1   30           15
55          56       0   26            4
56          57       1   26            8
57          58       0   25           10
58          59       1   30           12
59          60       0   31           15

In [336]:
target=df2['label'].dropna()
target

0     1
1     0
2     1
3     0
4     0
5     0
6     0
7     1
8     0
9     0
10    1
11    0
12    0
13    0
14    1
15    0
16    0
17    0
18    1
19    0
20    1
21    0
22    0
23    1
24    0
25    0
26    0
27    1
28    0
29    1
30    0
31    1
32    0
33    0
34    0
35    1
36    0
37    0
38    2
39    0
40    1
41    0
42    0
43    0
44    0
45    2
46    2
47    1
48    0
49    0
50    0
51    2
52    0
53    2
54    0
55    1
56    0
57    0
58    0
59    1
Name: label, dtype: int32

## logistic regression

In [339]:
from sklearn.linear_model import LogisticRegression as LR

In [340]:
lr=LR()

In [342]:
lr.fit(x_train,y_train)

C:\Users\numam\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [345]:
lr.score(x_test,y_test)

0.6

## K Nearest Neighbors Classifier

In [349]:
from sklearn.neighbors import KNeighborsClassifier as KNC

In [351]:
knc=KNC()

In [352]:
knc.fit(x_train,y_train)

KNeighborsClassifier()

In [360]:
knc.score(x_test,y_test)

0.4666666666666667